import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Navbar } from "@/components/Navbar";
import { HeroUIProvider } from "@heroui/system";

export const metadata: Metadata = {
  title: "LearningEnglish",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <HeroUIProvider>
          <main>
            <Navbar />
            {children}
          </main>
          <Toaster richColors toastOptions={{ className: "z-50" }} />
        </HeroUIProvider>
      </body>
    </html>
  );
}
