# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyalarını tek tek kopyala (bağımlılıklar için)
COPY ["src/EnglishCardApp.WebAPI/EnglishCardApp.WebAPI.csproj", "src/EnglishCardApp.WebAPI/"]
COPY ["src/EnglishCardApp.Application/EnglishCardApp.Application.csproj", "src/EnglishCardApp.Application/"]
COPY ["src/EnglishCardApp.Domain/EnglishCardApp.Domain.csproj", "src/EnglishCardApp.Domain/"]
COPY ["src/EnglishCardApp.Infrastructure/EnglishCardApp.Infrastructure.csproj", "src/EnglishCardApp.Infrastructure/"]

# Restore
RUN dotnet restore "src/EnglishCardApp.WebAPI/EnglishCardApp.WEbAPI.csproj"

# Şimdi tüm kaynak kodunu kopyala
COPY . .

# Build ve publish
WORKDIR /src/src/EnglishCardApp.API
RUN dotnet publish -c Release -o /app/publish

# 2. Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "EnglishCardApp.API.dll"]
